[project]
name = "nailong-workspace-scripts"
version = "0"
requires-python = "<4.0,>=3.9"
dependencies = []
license = { text = "MIT" }

[tool.pdm.dev-dependencies]
dev = []

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm]
distribution = false
